language: php

php:
  - 7.3
  - 7.4

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer require --dev --no-update squizlabs/php_codesniffer=*
  - travis_retry composer install --prefer-dist --no-interaction

script:
  - vendor/bin/phpcs
  - vendor/bin/phpunit --coverage-clover coverage.xml --exclude-group integration

after_success:
    - bash <(curl -s https://codecov.io/bash)
